services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "7104:80"
        environment:
          - ConnectionStrings:Default=Server=db;Database=tic-tac-toe;User ID=SA;Password=S3cur3P@ssW0rd!;Trust Server Certificate=True;
        depends_on:
          - db
    
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
          - MSSQL_SA_PASSWORD=S3cur3P@ssW0rd!
          - ACCEPT_EULA=Y