version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "7104:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
          - mssqllocaldb

    mssqllocaldb:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"