version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "7104:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ConnectionStrings:Default=Server=localhost,1433;Database=tic-tac-toe;User=mssql;Password=S3cur3P@ssW0rd!;
        depends_on:
          - db
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
          - MSSQL_SA_PASSWORD=S3cur3P@ssW0rd!
          - ACCEPT_EULA=Y